#
# Debian-based version for the container
#
FROM docker.io/ubuntu:noble AS runtime

ARG PKG_NAME=prtgmpprobe
ARG DEBIAN_FRONTEND=noninteractive

# PRTGMPPROBE__NAME
# PRTGMPPROBE__ID

ENV CONFIG_FILE=/config/config.yml
ENV PRTGMPPROBE__ID_FILE=/config/id.txt
ENV PRTGMPPROBE__MOMO__DIR="/opt/paessler/mpprobe/monitoringmodules/"
ENV PRTGMPPROBE__MAX_SCHEDULING_DELAY="300"
ENV PRTGMPPROBE__HEARTBEAT_INTERVAL="30"
# Will be set at runtime if empty
ENV PRTGMPPROBE__NATS__CLIENT_NAME=""
ENV PRTGMPPROBE__LOGGING__CONSOLE__LEVEL="info"
ENV PRTGMPPROBE__LOGGING__CONSOLE__WITHOUT_TIME="true"
ENV PRTGMPPROBE__LOGGING__JOURNALD__LEVEL="off"
ENV PRTGMPPROBE__LOGGING__JOURNALD__FIELD_PREFIX="PRTGMPROBE"

# Debian its base image already has lots of packages, which we will upgrade at once
RUN echo "Upgrading System Packages"; \
    apt-get update && \
    apt-get full-upgrade -y

# Install dependencies for the PRTG multi-platform probe itself
RUN echo "Installing Probe Dependencies"; \
    apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates \
        curl \
        gosu \
        python3-minimal && \
    apt-get clean

# Add the Paessler repository and install the probe package
RUN echo "Installing the apt repository"; \
    if curl -fsSL "https://packages.paessler.com/keys/paessler.asc" --output "/etc/apt/keyrings/paessler-archive-keyring.asc"; then \
        ln -s "/etc/apt/keyrings/paessler-archive-keyring.asc" "/usr/share/keyrings/paessler-archive-keyring.asc" && \
        echo "The Paessler apt key has been installed @ /etc/apt/keyrings/paessler-archive-keyring.asc"; \
    else \
        echo "Failed to install the Paessler apt key"; \
        exit 1; \
    fi; \
\
    . /etc/os-release && \
    if curl -fsSL "https://packages.paessler.com/docs/apt-sources/${VERSION_CODENAME}.sources" > "/etc/apt/sources.list.d/paessler.sources"; then \
        echo "The Paessler apt sources list has been installed @ /etc/apt/sources.list.d/paessler.sources"; \
    else \
        echo "Failed to install the Paessler apt sources list"; \
        exit 1; \
    fi

RUN echo "Installing the PRTG Multi-Platform Probe"; \
    apt-get update && \
    if [ -n "$(apt-cache search ^${PKG_NAME}$)" ]; then \
        echo "Found a matching package, installing..."; \
        apt-get install -y "${PKG_NAME}" && \
        echo "Successfully installed ${PKG_NAME}"; \
    else \
        echo "Failed to find a match for '${PKG_NAME}' in the apt cache"; \
        exit 1; \
    fi; \
    apt-get clean

# Configuration directory for the PRTG Multi-Platform Probe, for example a: config.yml
VOLUME /config
# Scripts directory for the Script v2 sensor
VOLUME /opt/paessler/share/scripts

COPY ./src/entrypoint.sh /entrypoint.sh

WORKDIR /config

# The entrypoint, which ALWAYS runs at startup as the first command
ENTRYPOINT ["/entrypoint.sh"]
