name: Commit lint

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - edited

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    container: commitlint/commitlint:20.5.1
    permissions:
      security-events: read
      packages: read
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: lint pull request title
        run: |
          echo "${{ github.event.pull_request.title }}" | commitlint --config .commitlintrc.json
